[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self';img-src 'self' https://res.cloudinary.com;style-src 'self' https://global.oktacdn.com;manifest-src 'self';object-src 'none'; script-src: https://global.oktacdn.com;form-action https:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(); geolocation=(); midi=(); notifications=(); push=(); sync-xhr=(); microphone=(); camera=(); magnetometer=(); gyroscope=(); speaker=(); vibrate=(); fullscreen=(); payment=()"
    X-Content-Type-Options = "nosniff"

[build]
  functions = "functions"


[[redirects]]
  from = "/api/*"
  to = "/api/login"
  status = 302

[[redirects]]
  from = "/api/dashboard/*"
  to = "/.netlify/functions/:splat"
  status = 200
